cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    meet:
      email: meetpatel8122001@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: meet
      password: $2b$12$4aiKAzcZXQWVfdEAybD0NeOpoyyxfpfoh.TNfKntf6ABPEBIm9yK6
pre-authorized:
  emails:
  - meetpatel8122001@gmail.com
