cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    meet:
      email: meetpatel8122001@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: meet
      password: $2b$12$4aiKAzcZXQWVfdEAybD0NeOpoyyxfpfoh.TNfKntf6ABPEBIm9yK6
    spandan99:
      email: Spandan@gmail.com
      logged_in: false
      name: Spandan
      password: $2b$12$NlEuLb7PHGH7kdfMBdtwo.Gr0MAQfP1q6PMiCeVdBZjHFu7aWaydK
pre-authorized:
  emails:
  - meetpatel8122001@gmail.com
