cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    meet:
      email: meet@gmail.com
      logged_in: false
      name: meet
      password: $2b$12$pWip1kAN8nBrCr6kL2NP3.FHZBOOSdyv3Jxv3XyD9kpai5Zfn9aAW
    spandan99:
      email: Spandan@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Spandan
      password: $2b$12$NlEuLb7PHGH7kdfMBdtwo.Gr0MAQfP1q6PMiCeVdBZjHFu7aWaydK
    srey:
      email: srey@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: srey
      password: $2b$12$C4K1NSicjxhC75ACVPGJsOn0THqALvGvWZcaLLryGoieu0R5d8hDS
pre-authorized:
  emails:
  - meetpatel8122001@gmail.com
